name: Application CI
on: [push, pull_request]
jobs:
    validation:
        name: "Gradle Wrapper Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
    pipeline:
        name: test2 pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Run backend test
              run: |
                  chmod +x gradlew
                  ./gradlew clean test integrationTest
            - name: Package application
              run: ./gradlew bootJar -Pprod -x test -x integrationTest
            - name: Install Snyk CLI
              run: |
                curl -Lo ./snyk $(curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url.*snyk-linux\"" | cut -d ':' -f 2,3 | tr -d \" | tr -d ' ')
                chmod +x snyk
            - name: Snyk Test
              run: ./snyk test --all-projects
            - name: Snyk Monitor
              run: ./snyk test --all-projects





